openapi: 3.0.0
info:
  title: DoctorsMeBizAPI
  version: '1.0'
servers:
  - url: 'http://localhost:3000/v1'
paths:
  /qa:
    post:
      summary: 相談投稿
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  eueuuuu:
                    type: string
      operationId: post-qa-post
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                qa_id:
                  type: string
                content:
                  type: string
                expert_category:
                  type: string
                user_id:
                  type: string
          application/xml:
            schema:
              type: object
              properties: {}
        description: ''
      description: 相談を投稿する
    parameters: []
    get:
      summary: 相談詳細取得
      operationId: get-qa
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QaDetail'
      security:
        - API_TOKEN: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                qa_id:
                  type: string
      description: 特定の相談内容を取得する。
  /qa/list:
    parameters: []
    get:
      summary: 相談履歴取得
      operationId: get-qa-list
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  qa_list:
                    type: array
                    items:
                      $ref: '#/components/schemas/Qa'
      security:
        - API_TOKEN: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
      description: 特定ユーザーの相談内容をすべて取得する。
  /user/signup:
    parameters: []
    post:
      summary: ユーザーサインアップ
      operationId: post-user-register
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
      description: ユーザーを登録して、user_idを得る。
      parameters: []
      security:
        - CLIENT_SECRET: []
        - CLIENT_ID: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                client_user_id:
                  type: string
                  description: goo_id
  /user/signin:
    post:
      summary: ユーザーサインイン
      operationId: post-user-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  API_TOKEN:
                    type: string
                  client_user_id:
                    type: string
      security:
        - CLIENT_SECRET: []
        - CLIENT_ID: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
          application/xml:
            schema:
              type: object
              properties: {}
          multipart/form-data:
            schema:
              type: object
              properties: {}
          text/html:
            schema:
              type: object
              properties: {}
          text/plain:
            schema:
              type: object
              properties: {}
          application/EDI-X12:
            schema:
              type: object
              properties: {}
          application/EDIFACT:
            schema:
              type: object
              properties: {}
          application/atom+xml:
            schema:
              type: object
              properties: {}
          application/font-woff:
            schema:
              type: object
              properties: {}
          application/gzip:
            schema:
              type: object
              properties: {}
        description: ''
      parameters: []
      description: user_idを利用して、他のAPI呼び出しに必要なAPI_TOKENを得る。
    parameters: []
components:
  schemas:
    QaRes:
      title: QaRes
      type: object
      x-examples:
        example-1:
          id: string
          content: string
          created: string
          upload_image_url: string
      properties:
        id:
          type: string
        content:
          type: string
        created:
          type: string
        upload_image_url:
          type: string
        author_type:
          type: string
    Qa:
      title: QA
      type: object
      properties:
        id:
          type: string
        created:
          type: string
        expert_category:
          type: string
        expert:
          $ref: '#/components/schemas/Expert'
        user_id:
          type: string
        status:
          type: string
          description: |2













































































































              #     START(10, "質問開始"), READY(20, "回答中"), STOP(21, "回答保留"), ANSWER(22, "回答済み"), AGAIN(30, "再質問"), FINISH(40, "質問終了"), FINISH_STAFF(
              #         41, "質問終了(スタッフ)"),;
        first_qa_res:
          $ref: '#/components/schemas/QaRes'
    User:
      title: User
      type: object
      properties:
        id:
          type: string
    Expert:
      title: Expert
      type: object
      properties:
        id:
          type: string
        nick_name:
          type: string
        icon_url:
          type: string
        expert_category:
          type: string
          description: |2













































































































                  when "chemist" then return "薬剤師"
                  when "doctor" then return "医師"
                  when "dietitian" then return "栄養士"
                  when "dentist" then return "歯科医"
                  when "pet" then return "獣医師"
    QaDetail:
      title: QaDetail
      type: object
      properties:
        id:
          type: string
        created:
          type: string
        expert_category:
          type: string
        expert:
          $ref: '#/components/schemas/Expert'
        qa_res_list:
          type: array
          items:
            $ref: '#/components/schemas/QaRes'
        user_id:
          type: string
        status:
          type: string
          description: |+

  securitySchemes:
    CLIENT_SECRET:
      name: ClientSecret
      type: apiKey
      in: header
    CLIENT_ID:
      name: ClientId
      type: apiKey
      in: header
    API_TOKEN:
      name: APIToken
      type: apiKey
      in: header
